-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
  FROM BOOK A
  JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
  JOIN BOOK_SALES C
    ON A.BOOK_ID = C.BOOK_ID
 WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
 GROUP
    BY A.AUTHOR_ID, CATEGORY
 ORDER
    BY A.AUTHOR_ID, CATEGORY DESC