SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT A.USER_ID) USERS
  FROM ONLINE_SALE B
  LEFT JOIN USER_INFO A
  ON A.USER_ID = B.USER_ID
 WHERE GENDER is not NULL
 GROUP
    BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
 ORDER
    BY YEAR, MONTH, GENDER