-- 코드를 입력하세요
SELECT DISTINCT CAR_ID,
  CASE
    WHEN CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A WHERE END_DATE >= '2022-10-16' AND START_DATE <= '2022-10-16') THEN '대여중'
    ELSE '대여 가능'
  END AS 'AVAILAVILITY'
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 ORDER
    BY CAR_ID DESC