WITH RECURSIVE TEMP AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM TEMP
    WHERE NUM<23
),
CNT AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)

SELECT 
    CASE
        WHEN CNT.HOUR IN (SELECT NUM FROM TEMP) THEN CNT.HOUR
        ELSE TEMP.NUM
    END AS HOUR,
    CASE
        WHEN CNT.HOUR IN (SELECT NUM FROM TEMP) THEN CNT.COUNT
        ELSE 0
    END AS COUNT
FROM TEMP
LEFT JOIN CNT 
       ON TEMP.NUM = CNT.HOUR

  