SELECT A.CATEGORY, MAX_PRICE, PRODUCT_NAME
  FROM FOOD_PRODUCT AS A
  JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
  FROM FOOD_PRODUCT
 GROUP
    BY CATEGORY) AS B
    ON A.CATEGORY = B.CATEGORY
 WHERE A.PRICE = MAX_PRICE AND A.CATEGORY IN ('과자','국','김치','식용유')
 ORDER
    BY MAX_PRICE DESC